services:
  web:
    build: ./web
    ports:
      - "8001:8000"
    deploy:
      resources:
        limits:
          memory: 6G     
        reservations:
          memory: 2G
    command: sh release.sh

    volumes:
      - ./web:/code

    env_file:
      - ./.env

  gotenberg:
    image: gotenberg/gotenberg:8
    deploy:
      resources:
        limits:
          memory: 3G     
        reservations:
          memory: 1G

volumes:
  postgres_data:
