services:
  web:
    build: ./web
    ports:
      - "8001:8000"

    command: uvicorn config.asgi:application --reload --host 0.0.0.0 --port 8000


    volumes:
      - ./web:/code
    depends_on:
      - db
      - embeddings
    env_file:
      - ./.env.dev
  
  gotenberg:
    image: gotenberg/gotenberg:8

  # we recommend running a managed version of Postgres in production (RDS, GCP, etc)
  db:
    image: pgvector/pgvector:pg16
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"

  # we recommend running serverless GPU functions in production (Lambda, RunPod, etc)
  embeddings:
    image: tjmlabs/yarr-embedding-service:20241002-local
    ports:
      - "8000:8000"


    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    
volumes:
  postgres_data: