services:
  web:
    build: ./web
    ports:
      - "8001:8000"

    command: uvicorn config.asgi:application --reload --host 0.0.0.0 --port 8000


    volumes:
      - ./web:/code
    depends_on:
      - db
    env_file:
      - ./.env.dev
  
  gotenberg:
    image: gotenberg/gotenberg:8


  db:
    image: pgvector/pgvector:pg16
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"


  embeddings:
    build: ./embedding
    command: uvicorn handler:app --host 0.0.0.0 --port 8000 --reload
    
    
    # uncomment the following lines to deploy on GPU
    # make sure to install the nvidia-container-toolkit on your host machine

    #deploy:
      #resources:
        #reservations:
          #devices:
            #- driver: nvidia
              #count: 1 or all
              #capabilities: [gpu]

    
volumes:
  postgres_data: