services:
  web:
    build: ./web
    ports:
      - "8001:8000"
    deploy:
      resources:
        limits:
          memory: 6G     
        reservations:
          memory: 2G
    command: sh release.sh

    volumes:
      - ./web:/code

    env_file:
      - ./.env

  gotenberg:
    image: gotenberg/gotenberg:8
    deploy:
      resources:
        limits:
          memory: 3G     
        reservations:
          memory: 1G

  redis:
      image: "redis:alpine"
      command: redis-server --maxmemory 2gb --maxmemory-policy allkeys-lru
      ports:
        - "6379:6379"
      volumes:
        - redis_data:/data
      deploy:
        resources:
          limits:
            memory: 3gb 

volumes:
  redis_data: