on:
  pull_request:
    branches: [main]

  # on demand
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        working-directory: ./web
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.in

      - name: Run mypy
        working-directory: ./web
        run: mypy .
